CREATE TABLE IF NOT EXISTS reading_records (
  book_id INTEGER PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
