use crate::domain::source::{BookSource, CatalogRule, InfoRule, RawSourceRules, SearchRule};

#[derive(sqlx::FromRow)]
pub(super) struct SourceRow {
    id: i64,
    name: String,
    base_url: String,
    search_url: String,
    explore_url: Option<String>,
    search_item_selector: String,
    title_selector: String,
    author_selector: Option<String>,
    cover_selector: Option<String>,
    url_selector: String,
    info_title_selector: Option<String>,
    info_author_selector: Option<String>,
    info_intro_selector: Option<String>,
    info_cover_selector: Option<String>,
    catalog_item_selector: Option<String>,
    catalog_title_selector: Option<String>,
    catalog_url_selector: Option<String>,
    content_selector: Option<String>,
    next_toc_url_selector: Option<String>,
    next_content_url_selector: Option<String>,
    enabled: i64,
    header: Option<String>,
    login_url: Option<String>,
    login_method: String,
    login_body: Option<String>,
    token_path: Option<String>,
    access_token: Option<String>,
    session_cookie: Option<String>,
    session_expires_at: Option<String>,
    sign_script: Option<String>,
    proxy_url: Option<String>,
    concurrent_rate: Option<String>,
    rule_search: Option<String>,
    rule_book_info: Option<String>,
    rule_toc: Option<String>,
    rule_content: Option<String>,
    rule_explore: Option<String>,
    source_group: Option<String>,
    custom_order: i64,
    weight: i64,
    enabled_explore: i64,
    respond_time: Option<i64>,
    last_update_time: Option<i64>,
}

pub(super) fn map_source(row: SourceRow) -> BookSource {
    BookSource {
        id: row.id,
        name: row.name,
        base_url: row.base_url,
        search_url: row.search_url,
        explore_url: row.explore_url,
        search_rule: SearchRule {
            item: row.search_item_selector,
            title: row.title_selector,
            author: row.author_selector,
            cover: row.cover_selector,
            url: row.url_selector,
        },
        info_rule: InfoRule {
            title: row.info_title_selector,
            author: row.info_author_selector,
            intro: row.info_intro_selector,
            cover: row.info_cover_selector,
            kind: None,
            latest_chapter: None,
        },
        catalog_rule: CatalogRule {
            item: row.catalog_item_selector.unwrap_or_else(|| "a".into()),
            title: row.catalog_title_selector.unwrap_or_else(|| "a".into()),
            url: row
                .catalog_url_selector
                .unwrap_or_else(|| "a::attr(href)".into()),
            next_url: row.next_toc_url_selector.clone(),
        },
        content_selector: row.content_selector.unwrap_or_else(|| "body".into()),
        next_toc_url_selector: row.next_toc_url_selector,
        next_content_url_selector: row.next_content_url_selector,
        header: row.header,
        login_url: row.login_url,
        login_method: row.login_method,
        login_body: row.login_body,
        token_path: row.token_path,
        access_token: row.access_token,
        session_cookie: row.session_cookie,
        session_expires_at: row.session_expires_at,
        sign_script: row.sign_script,
        proxy_url: row.proxy_url,
        concurrent_rate: row.concurrent_rate,
        enabled: row.enabled != 0,
        source_group: row.source_group,
        custom_order: row.custom_order,
        weight: row.weight,
        enabled_explore: row.enabled_explore != 0,
        respond_time: row.respond_time,
        last_update_time: row.last_update_time,
        raw_rules: RawSourceRules {
            search: row.rule_search,
            book_info: row.rule_book_info,
            toc: row.rule_toc,
            content: row.rule_content,
            explore: row.rule_explore,
        },
    }
}

pub(super) const SOURCE_SELECT: &str = "SELECT id, name, base_url, search_url, explore_url, search_item_selector, title_selector, author_selector, cover_selector, url_selector, info_title_selector, info_author_selector, info_intro_selector, info_cover_selector, catalog_item_selector, catalog_title_selector, catalog_url_selector, content_selector, next_toc_url_selector, next_content_url_selector, enabled, header, login_url, login_method, login_body, token_path, access_token, session_cookie, session_expires_at, sign_script, proxy_url, concurrent_rate, rule_search, rule_book_info, rule_toc, rule_content, rule_explore, source_group, custom_order, weight, enabled_explore, respond_time, last_update_time FROM book_sources";
