use std::{collections::HashMap, time::Duration};
use uuid::Uuid;

use super::*;
use std::io::{Read, Write};
use std::net::TcpListener;

#[tokio::test]
async fn executes_expression_and_java_helpers() {
    let runtime = QuickJsRuntime::default();
    let value = runtime
        .execute(
            "java.base64Encode(result)",
            JsContext {
                result: "hello".into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("aGVsbG8=".into()));
}

#[tokio::test]
async fn reads_and_writes_context_variables() {
    let runtime = QuickJsRuntime::default();
    let mut variables = HashMap::new();
    variables.insert("id".into(), "42".into());
    let value = runtime
        .execute(
            "java.put('id', java.get('id') + '0')",
            JsContext {
                variables,
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("420".into()));
}

#[tokio::test]
async fn rejects_empty_script() {
    let error = QuickJsRuntime::default()
        .execute(" ", JsContext::default())
        .await
        .unwrap_err();
    assert!(matches!(error, AppError::InvalidArgument(_)));
}

#[tokio::test]
async fn reports_the_javascript_exception_message() {
    let error = QuickJsRuntime::default()
        .execute("missingHelper()", JsContext::default())
        .await
        .unwrap_err()
        .to_string();
    assert!(error.contains("missingHelper"), "{error}");
    assert!(!error.contains("Exception generated by QuickJS"), "{error}");
}

#[tokio::test]
async fn executes_newline_separated_statement_scripts() {
    let script = r#"
signKey='secret'
headers={'platform':'android'}
params={'page':page,'wd':key}
var encode = function(values) {
  return Object.keys(values).map(k=>k+'='+values[k]).join('&')
};
headerSign=java.md5Encode(encode(headers)+signKey)
paramSign=java.md5Encode(encode(params)+signKey)
headers['sign']=headerSign
params['sign']=paramSign
'/search?'+encode(params)+','+JSON.stringify({'headers':headers})
"#;
    let value = QuickJsRuntime::default()
        .execute(
            script,
            JsContext {
                key: Some("斗破苍穹".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    match value {
        JsValue::String(value) => {
            assert!(value.starts_with("/search?page=1&wd="), "{value}");
            assert!(value.contains("headers"), "{value}");
        }
        other => panic!("unexpected result: {other:?}"),
    }
}

#[tokio::test]
async fn executes_pretty_printed_comma_declarations() {
    // Real corpus shape (source[260].ruleToc.chapterList): a declaration is
    // split across two lines by a comma, and the whole script used to abort
    // with "variable name expected" before the rule's intent was ever reached.
    // The element API itself (`d.select`/`push`) is a separate gap (E0/Jsoup),
    // so this test pins the *statement* the declaration produced.
    let script = "\nvar list = [],\nd = java.getElement('.item');\nlist.push(d)\nlist.length + ':' + (typeof d)\n";
    let value = QuickJsRuntime::default()
        .execute(
            script,
            JsContext {
                result: r#"<div class="item"><a class="name">audit</a></div>"#.into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    match value {
        JsValue::String(value) => assert!(value.starts_with("1:"), "{value}"),
        other => panic!("unexpected result: {other:?}"),
    }
}

#[tokio::test]
async fn executes_real_qimao_search_script() {
    let script = r#"
sign_key='d3dGiJc651gSQ8w1'

headers={'app-version':'51110','platform':'android','reg':'0','AUTHORIZATION':'','application-id':'com.****.reader','net-env':'1','channel':'unknown','qm-params':''}

params={'gender':'3','imei_ip':'2937357107','page':page,'wd':key}

var urlEncode = function (param, key, encode) {
  if(param==null) return '';
  var paramStr = '';
  var t = typeof (param);
  if (t == 'string' || t == 'number' || t == 'boolean') {
paramStr += '&' + key + '=' + ((encode==null||encode) ? encodeURIComponent(param) : param);
  } else {
for (var i in param) {
  var k = key == null ? i : key + (param instanceof Array ? '[' + i + ']' : '.' + i);
  paramStr += urlEncode(param[i], k, encode);
}
  }
  return paramStr;
};

headerSign=String(java.md5Encode(Object.keys(headers).sort().reduce((pre,n)=>pre+n+'='+headers[n],'' )+sign_key))
paramSign=String(java.md5Encode(Object.keys(params).sort().reduce((pre,n)=>pre+n+'='+params[n],'' )+sign_key))
headers['sign']=headerSign
params['sign']=paramSign
body=urlEncode(params)

"/api/v5/search/words?" +body+","+java.put("headers",JSON.stringify({"headers":headers}))"#;
    let value = QuickJsRuntime::default()
        .execute(
            script,
            JsContext {
                key: Some("斗破苍穹".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert!(matches!(value, JsValue::String(value) if value.starts_with("/api/v5/search/words?")));
}

#[tokio::test]
async fn executes_statement_scripts_starting_with_control_flow() {
    let value = QuickJsRuntime::default()
        .execute(
            "if (key) { result = key; }\nresult",
            JsContext {
                key: Some("ok".into()),
                result: "before".into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("ok".into()));
}

#[tokio::test]
async fn executes_legado_control_flow_after_function_declarations() {
    let value = QuickJsRuntime::default()
        .execute(
            r#"
var category = function () { return 'category'; };
var tag = function () { return 'tag'; };
if (baseUrl.match(/category/)) {
  category()
} else {
  tag()
}
"#,
            JsContext {
                base_url: Some("https://example.test/tag".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("tag".into()));
}

#[tokio::test]
async fn accepts_legado_one_argument_ajax_calls() {
    let error = QuickJsRuntime::default()
        .execute(
            "java.ajax('not a valid URL')",
            JsContext {
                http: Some(JsHttpContext::default()),
                ..Default::default()
            },
        )
        .await
        .unwrap_err()
        .to_string();
    assert!(!error.contains("argument(s)"), "{error}");
    assert!(error.contains("network error"), "{error}");
}

#[tokio::test]
async fn blocking_execution_with_http_context_is_safe_inside_async_context() {
    let value = QuickJsRuntime::default()
        .execute_blocking(
            "result",
            JsContext {
                result: "safe".into(),
                http: Some(JsHttpContext::default()),
                ..Default::default()
            },
        )
        .unwrap();
    assert_eq!(value, JsValue::String("safe".into()));
}

#[tokio::test]
async fn exposes_encoding_and_time_helpers() {
    let runtime = QuickJsRuntime::default();
    let value = runtime
        .execute(
            "java.hexEncodeToString('Hi') + '|' + java.hexDecodeToString('4869') + '|' + java.md5Encode('hello') + '|' + java.strToBytes('Hi') + '|' + java.bytesToStr('72,105') + '|' + java.timeFormat(0, 'yyyy-MM-dd HH:mm:ss')",
            JsContext::default(),
        )
        .await
        .unwrap();
    assert_eq!(
        value,
        JsValue::String(
            "4869|Hi|5d41402abc4b2a76b9719d911017c592|72,105|Hi|1970-01-01 00:00:00".into()
        )
    );
    assert_eq!(
        QuickJsRuntime::default()
            .execute("java.timeFormat(0)", JsContext::default())
            .await
            .unwrap(),
        JsValue::String("1970-01-01 00:00:00".into())
    );
    assert_eq!(
        QuickJsRuntime::default()
            .execute(
                "java.timeFormatUTC(0, 'yyyy-MM-dd HH:mm:ss', 8)",
                JsContext::default()
            )
            .await
            .unwrap(),
        JsValue::String("1970-01-01 08:00:00".into())
    );
}

#[tokio::test]
async fn exposes_common_conversion_helpers() {
    let value = QuickJsRuntime::default()
        .execute(
            "java.decodeURI('a%20b') + '|' + java.toInt(' 42 ') + '|' + java.toBoolean('YES') + '|' + java.isNull(null)",
            JsContext::default(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("a b|42|true|true".into()));
}

#[tokio::test]
async fn exposes_digest_hmac_and_uuid_helpers() {
    let value = QuickJsRuntime::default()
        .execute(
            "java.digestHex('hello', 'SHA-256') + '|' + java.HMacHex('hello', 'HmacSHA256', 'key') + '|' + java.HMacBase64('hello', 'HmacSHA1', 'key') + '|' + java.randomUUID()",
            JsContext::default(),
        )
        .await
        .unwrap();
    let JsValue::String(value) = value else {
        panic!("expected string result")
    };
    let pieces = value.split('|').collect::<Vec<_>>();
    assert_eq!(
        pieces[0],
        "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
    );
    assert_eq!(pieces[1].len(), 64);
    assert_eq!(pieces[2].len(), 28);
    assert!(Uuid::parse_str(pieces[3]).is_ok());
}

#[tokio::test]
async fn exposes_nested_rule_helpers() {
    let runtime = QuickJsRuntime::default();
    let value = runtime
        .execute(
            "java.getString('$.book.name')",
            JsContext {
                result: r#"{"book":{"name":"斗破苍穹"}}"#.into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("斗破苍穹".into()));

    let value = runtime
        .execute(
            "java.getElements('tag.li').length + ':' + java.getElement('tag.li')",
            JsContext {
                result: "<ul><li>一</li><li>二</li></ul>".into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert!(
        matches!(value, JsValue::String(value) if value.starts_with("2:") && value.contains("<li>一</li>"))
    );
}

#[tokio::test]
async fn exposes_the_jsoup_element_and_java_collection_api() {
    let runtime = QuickJsRuntime::default();
    let context = || JsContext {
        result: r#"<div class="row"><a href="/one" data-id="2">一</a><a href="/two" data-id="1">二</a></div>"#
            .into(),
        ..Default::default()
    };
    // JSoup's `Elements`: size() / attr() / text() on the collection itself.
    let value = runtime
        .execute(
            "java.getElements('.row a').size() + '|' + java.getElements('.row a').attr('href') + '|' + java.getElements('.row a').text()",
            context(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("2|/one|一 二".into()));

    // `toArray()` yields elements, not strings, so `.attr()` keeps working.
    let value = runtime
        .execute(
            "java.getElements('.row a').toArray().map(x => x.attr('data-id')).sort().join(',')",
            context(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("1,2".into()));

    // Element-level `select()` / `get()`, and index access on the collection.
    let value = runtime
        .execute(
            "java.getElement('.row').select('a').get(1).text() + '|' + java.getElements('.row a')[0].text()",
            context(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("二|一".into()));

    // Java's `ArrayList<String>`: size() / toArray() alongside the JS array API.
    let value = runtime
        .execute(
            "java.getStringList('a@href').size() + '|' + java.getStringList('a@href').toArray().join('+')",
            context(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("2|/one+/two".into()));
}

#[tokio::test]
async fn normalizes_chapter_numbers_and_ignores_android_toasts() {
    let value = QuickJsRuntime::default()
        .execute(
            "java.toast('ignored'); java.longToast('ignored'); java.toNumChapter('第一百二十三章')",
            JsContext::default(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("第123章".into()));
}

#[tokio::test]
async fn exposes_authentication_state_to_source_scripts() {
    let runtime = QuickJsRuntime::default();
    let value = runtime
        .execute(
            "java.sessionState() + ':' + java.isAuthenticated()",
            JsContext {
                http: Some(JsHttpContext {
                    access_token: Some("token".into()),
                    ..Default::default()
                }),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("authenticated:true".into()));
}

#[tokio::test]
async fn exposes_a_stable_desktop_android_id_compatibility_helper() {
    let runtime = QuickJsRuntime::default();
    let first = runtime
        .execute(
            "java.androidId()",
            JsContext {
                base_url: Some("https://example.test".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    let second = runtime
        .execute(
            "java.androidId()",
            JsContext {
                base_url: Some("https://example.test".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(first, second);
    assert!(matches!(first, JsValue::String(value) if value.len() == 16));
}

#[tokio::test]
async fn exposes_expired_state_without_authenticating_scripts() {
    let runtime = QuickJsRuntime::default();
    let value = runtime
        .execute(
            "java.sessionState() + ':' + java.isAuthenticated()",
            JsContext {
                http: Some(JsHttpContext {
                    access_token: Some("token".into()),
                    session_expired: true,
                    ..Default::default()
                }),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::String("expired:false".into()));
}

#[tokio::test]
async fn exposes_legado_src_and_title_aliases() {
    let value = QuickJsRuntime::default()
        .execute(
            "src + '|' + title",
            JsContext {
                result: "body".into(),
                src: Some("https://example.test/chapter".into()),
                title: Some("第一章".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert_eq!(
        value,
        JsValue::String("https://example.test/chapter|第一章".into())
    );
}

#[tokio::test]
async fn exposes_common_rhino_global_aliases() {
    let value = QuickJsRuntime::default()
        .execute(
            "org + '|' + run + '|' + getUrl() + '|' + uuid().length",
            JsContext {
                result: "body".into(),
                base_url: Some("https://example.test".into()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    assert!(
        matches!(value, JsValue::String(value) if value.starts_with("body|body|https://example.test|36"))
    );
}

#[tokio::test]
async fn tolerates_redeclared_lexical_variables() {
    let value = QuickJsRuntime::default()
        .execute(
            "let value = 1; let value = 2; const value2 = 3; const value2 = 4; value + value2",
            JsContext::default(),
        )
        .await
        .unwrap();
    assert_eq!(value, JsValue::Number(6.0));
}

#[tokio::test]
async fn request_options_and_response_metadata_are_available_to_scripts() {
    let listener = TcpListener::bind(("127.0.0.1", 0)).unwrap();
    let address = listener.local_addr().unwrap();
    let server = std::thread::spawn(move || {
        let (mut stream, _) = listener.accept().unwrap();
        stream
            .set_read_timeout(Some(Duration::from_millis(500)))
            .unwrap();
        let mut bytes = Vec::new();
        let mut buffer = [0_u8; 4096];
        loop {
            match stream.read(&mut buffer) {
                Ok(0) | Err(_) => break,
                Ok(size) => {
                    bytes.extend_from_slice(&buffer[..size]);
                    let request = String::from_utf8_lossy(&bytes);
                    let expected = request
                        .split("\r\n\r\n")
                        .next()
                        .and_then(|headers| {
                            headers.lines().find_map(|line| {
                                line.strip_prefix("Content-Length:")?
                                    .trim()
                                    .parse::<usize>()
                                    .ok()
                            })
                        })
                        .unwrap_or_default();
                    if let Some(body) = request.split_once("\r\n\r\n").map(|(_, body)| body) {
                        if body.len() >= expected {
                            break;
                        }
                    }
                }
            }
        }
        let request = String::from_utf8_lossy(&bytes);
        assert!(request.to_ascii_lowercase().contains("x-test: yes"));
        assert!(request.contains("hello"));
        stream
            .write_all(
                b"HTTP/1.1 201 Created\r\nX-Trace: runtime\r\nContent-Type: text/plain\r\nContent-Length: 2\r\n\r\nok",
            )
            .unwrap();
    });
    let script = format!(
        "java.request('http://{address}', {{method:'POST', body:'hello', headers:{{'X-Test':'yes'}}, timeout:2000}}) + '|' + java.responseStatus() + '|' + java.responseHeader('x-trace') + '|' + JSON.parse(java.responseHeaders())['content-type']"
    );
    let value = QuickJsRuntime::default()
        .execute(
            &script,
            JsContext {
                http: Some(JsHttpContext::default()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    server.join().unwrap();
    assert_eq!(value, JsValue::String("ok|201|runtime|text/plain".into()));
}

#[tokio::test]
async fn terminates_infinite_loop_scripts_within_timeout() {
    let runtime = QuickJsRuntime::new(Duration::from_millis(300), 16 * 1024 * 1024);
    let started = std::time::Instant::now();
    let error = runtime
        .execute("while (true) {}", JsContext::default())
        .await
        .unwrap_err();
    assert!(
        started.elapsed() < Duration::from_secs(5),
        "infinite loop should be interrupted by the QuickJS interrupt handler"
    );
    assert!(
        error.to_string().contains("interrupted") || error.to_string().contains("超时"),
        "{error}"
    );
}
